Repository popi-official/popi-manager-client, pull requests merged in 2025-05, with the labels that each got.

#17 feat: 대시보드 방문자 분석 UI 구현
  src/components/common/DropdownFilter.tsx
  src/mocks/handlers/dashboard/VisitorDatas.ts
  src/pages/dashboard/DashBoard.tsx
  src/pages/dashboard/views/BestProduct.tsx
  src/pages/dashboard/views/DashBoardVisitor.tsx
  src/utils/VisitorColorMapper.tsx
Labels: ✨ feature

#19 fix: 대시보드 팝업스토어 방문자 분석 UI 구현
  src/components/common/CustomTooltip.tsx
  src/pages/dashboard/views/DashBoardVisitor.tsx
  src/pages/dashboard/views/VisitorPieChart.tsx
Labels: 🐛 bug/error

#24 chore : 테스트 세팅 수정 및 README 개선
  .github/workflows/CI.yml
  README.md
  jest.config.ts
  package-lock.json
  package.json
  src/apis/README.md
  src/assets/README.md
  src/assets/fonts/GmarketSansTTFMedium.ttf
  src/assets/fonts/PretendardVariable.woff2
  src/components/README.md
  src/components/boundary/CustomErrorBoundary.tsx
  src/components/boundary/CustomErrorFallback.tsx
  src/components/boundary/CustomQueryProvider.tsx
  src/components/boundary/DefaultBoundary.tsx
  src/components/boundary/README.md
  src/components/layouts/GlobalLayout.tsx
  src/constants/README.md
  src/fonts/README.md
  src/hooks/README.md
  src/hooks/useTest.ts
  src/index.css
  src/mocks/README.md
  src/pages/README.md
  src/router/README.md
  src/stores/README.md
  src/types/README.md
  src/types/api/ApiRequestType.ts
  src/types/api/ApiResponseType.ts
  src/utils/README.md
  tsconfig.app.json
  tsconfig.json
  vitest.config.ts
  vitest.storybook.config.ts
  vitest.workspace.ts
Labels: ⚙️ chore

#18 feat: 대시보드 구매전환율 UI 구현
  src/components/common/CustomBlurDot.tsx
  src/components/common/CustomCursor.tsx
  src/components/common/CustomTooltip.tsx
  src/mocks/handlers/dashboard/ConversionRateDatas.ts
  src/pages/dashboard/DashBoard.tsx
  src/pages/dashboard/views/CongestionChart.tsx
  src/pages/dashboard/views/ConversionRateChart.tsx
  src/pages/dashboard/views/DashBoardCongestion.tsx
  src/pages/dashboard/views/DashBoardConversionRate.tsx
  src/pages/dashboard/views/DashBoardReservation.tsx
  src/pages/dashboard/views/ReservationByDayChart.tsx
  src/types/ConversionRateType.ts
Labels: ✨ feature

#20 feat: 대시보드 설문지 분석 UI 구현
  chromatic.config.json
  src/mocks/handlers/dashboard/Questionnaire.ts
  src/pages/dashboard/DashBoard.tsx
  src/pages/dashboard/views/DashBoardQuestionnaire.stories.tsx
  src/pages/dashboard/views/DashBoardQuestionnaire.tsx
  src/pages/popUpCreate/PopUpCreate.tsx
  src/types/QuestionnaireType.ts
Labels: ✨ feature

#21 feat: Global Skeleton 컴포넌트 구현
  src/components/common/Skeleton.tsx
Labels: ✨ feature

#28 feat: 팝업 리스트 페이지 조회 기능 구현
  src/apis/PopUpCreateApi.ts
  src/apis/PopUpListReadApi.ts
  src/hooks/api/usePopUpListReadApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/popUpCreate/PopUpCreate.handlers.ts
  src/mocks/handlers/popUpList/PopUpCards.ts
  src/mocks/handlers/popUpListRead/popUpListRead.handlers.ts
  src/pages/popUpCreatePage/views/PopUpInfoArea.tsx
  src/pages/popUpListPage/PopUpListPage.tsx
  src/pages/popUpListPage/views/PopUpCard.tsx
  src/stores/usePopUpCreateStore.ts
  src/types/api/ApiRequestType.ts
  src/types/api/ApiResponseType.ts
Labels: ✨ feature

#29 faet: 상품 리스트 페이지 조회 기능 구현
  src/apis/ItemListApi.ts
  src/hooks/api/usePopUpListApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/Item.handlers.ts
  src/mocks/handlers/dashboard/BestItems.ts
  src/mocks/handlers/itemList/ItemListRead.handlers.ts
  src/pages/itemListPage/ItemListPage.tsx
  src/pages/itemListPage/views/ItemDisplay.tsx
  src/types/ImageExtenstionType.ts
  src/types/ItemType.ts
  src/types/api/ApiResponseType.ts
  src/utils/FileInfoExtract.ts
Labels: ✨ feature

#31 feat: 팝업 전역 상태관리 기능 구현
  src/pages/popUpListPage/views/PopUpCard.tsx
  src/stores/useAuthStore.ts
  src/stores/usePopUpReadStore.ts
Labels: ✨ feature

#32 feat: 상품 삭제 기능 구현
  src/apis/ItemCreateApi.ts
  src/apis/ItemListApi.ts
  src/hooks/api/useItemListApi.ts
  src/hooks/api/usePopUpListApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/itemCreate/ItemCreate.handlers.ts
  src/mocks/handlers/itemList/ItemList.handlers.ts
  src/mocks/handlers/itemList/ItemListRead.handlers.ts
  src/mocks/handlers/popUpCreate/PopUpCreate.handlers.ts
  src/pages/itemListPage/ItemListPage.tsx
  src/pages/itemListPage/views/ItemDisplay.tsx
  src/types/ItemType.ts
Labels: ✨ feature

#35 feat: 예약자 수 조회 기능 구현
  src/apis/DashBoardApi.ts
  src/hooks/api/useDashboardApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/dashboard/ReservationDatas.ts
  src/pages/dashboardPage/views/DashBoardReservation.tsx
  src/pages/dashboardPage/views/ReservationByDayChart.tsx
  src/types/ReservationType.ts
  src/types/api/ApiResponseType.ts
  src/utils/ReservationColorMapper.ts
Labels: ✨ feature

#36 feat: 재고 알람 기능 구현
  src/apis/StockNotificationListApi.ts
  src/components/common/NavBar.tsx
  src/components/noticeModal/NoticeModal.tsx
  src/components/noticeModal/views/NoticeItem.tsx
  src/hooks/api/useStockNotificationListApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/noticeModal/NoticeItems.ts
  src/mocks/handlers/noticeModal/StockNotificationList.handlers.ts
  src/pages/popUpListPage/PopUpListPage.tsx
  src/types/NoticeItemType.ts
  src/types/api/ApiResponseType.ts
Labels: ✨ feature

#39 feat: 엑셀 등록 기능 구현
  src/apis/ItemListApi.ts
  src/hooks/api/useItemCreateApi.ts
  src/hooks/useItemCreate.ts
  src/mocks/handlers/itemList/ItemList.handlers.ts
  src/pages/itemListPage/ItemListPage.tsx
  src/pages/itemListPage/views/ItemCreateExcelModal.tsx
  src/pages/itemListPage/views/ItemDisplay.tsx
  src/router/Router.tsx
  src/types/api/ApiRequestType.ts
Labels: ✨ feature

#40 feat: 로그아웃 API 추가
  src/apis/user/AuthApi.ts
  src/hooks/api/useAuthApi.ts
  src/hooks/useAuth.ts
  src/mocks/Logout.handlers.ts
  src/mocks/browser.ts
Labels: ✨ feature

#41 feat: 인기상품 조회 기능 구현
  src/apis/DashBoardApi.ts
  src/components/common/DropdownFilter.tsx
  src/hooks/api/useDashboardApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/dashboard/BestItems.ts
  src/pages/dashboardPage/views/BestItem.tsx
  src/types/DashboardType.ts
  src/types/ItemType.ts
  src/types/api/ApiRequestType.ts
  src/types/api/ApiResponseType.ts
Labels: ✨ feature

#37 feat: 대시보드 혼잡도 분석 조회 기능 구현
  src/apis/DashBoardApi.ts
  src/hooks/api/useDashboardApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/dashboard/CongestionRead.handlers.ts
  src/pages/dashboardPage/views/CongestionChart.tsx
  src/pages/dashboardPage/views/DashBoardCongestion.tsx
  src/pages/itemCreatePage/ItemCreatePage.tsx
  src/types/CongestionType.ts
  src/types/api/ApiResponseType.ts
Labels: ✨ feature

#43 feat: 설문지 분석 기능 구현
  src/apis/DashBoardApi.ts
  src/hooks/api/useDashboardApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/dashboard/Questionnaire.ts
  src/pages/dashboardPage/views/DashBoardQuestionnaire.tsx
  src/types/QuestionnaireType.ts
  src/types/api/ApiResponseType.ts
Labels: ✨ feature

#45 refactor: tanstack-query 캐시 전략 구성
  src/hooks/api/useItemCreateApi.ts
  src/hooks/api/useItemListApi.ts
  src/hooks/api/usePopUpCreateApi.ts
Labels: ♻️ refactor

#44 feat: 대시보드 구매 전환율 조회 기능 구현
  src/apis/DashBoardApi.ts
  src/hooks/api/useDashboardApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/dashboard/ConversionRateDatas.ts
  src/mocks/handlers/dashboard/ConversionRead.handlers.ts
  src/pages/dashboardPage/views/ConversionRateChart.tsx
  src/pages/dashboardPage/views/DashBoardCongestion.tsx
  src/pages/dashboardPage/views/DashBoardConversionRate.tsx
  src/types/api/ApiResponseType.ts
Labels: ✨ feature

#46 feat: 방문자 기능 구현
  src/apis/DashBoardApi.ts
  src/components/common/CustomTooltip.tsx
  src/hooks/api/useDashboardApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/dashboard/VisitorDatas.ts
  src/pages/dashboardPage/views/DashBoardVisitor.tsx
  src/pages/dashboardPage/views/VisitorPieChart.tsx
  src/types/api/ApiResponseType.ts
  src/utils/VisitorColorMapper.tsx
Labels: ✨ feature

#48 refactor: 코드 품질 개선 1차
  src/apis/DashBoardApi.ts
  src/apis/ItemCreateApi.ts
  src/apis/ItemListApi.ts
  src/apis/PopUpListReadApi.ts
  src/apis/StockNotificationListApi.ts
  src/apis/config/PopUpApi.ts
  src/assets/webps/dashboard/sad.webp
  src/assets/webps/onBoarding/onBorading2.webp
  src/assets/webps/onBoarding/onBorading3.webp
  src/components/common/CustomInput.tsx
  src/components/common/NavBar.tsx
  src/components/common/NoDataComp.tsx
  src/components/layouts/GlobalLayout.tsx
  src/components/noticeModal/NoticeModal.tsx
  src/components/noticeModal/views/NoticeItem.tsx
  src/constants/NavigationItems.ts
  src/constants/onboarding/ContentDesc.ts
  src/hooks/api/useDashboardApi.ts
  src/hooks/api/useItemCreateApi.ts
  src/hooks/api/usePopUpDeleteApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/dashboard/BestItems.handlers.ts
  src/mocks/handlers/dashboard/CongestionRead.handlers.ts
  src/mocks/handlers/dashboard/ConversionRead.handlers.ts
  src/mocks/handlers/dashboard/CustomerTransactionDatas.handlers.ts
  src/mocks/handlers/dashboard/Questionnaire.handlers.ts
  src/mocks/handlers/dashboard/ReservationDatas.handlers.ts
  src/mocks/handlers/dashboard/VisitorDatas.handlers.ts
  src/mocks/handlers/itemCreate/ItemCreate.handlers.ts
  src/mocks/handlers/itemList/ItemList.handlers.ts
  src/mocks/handlers/popUpCreate/PopUpCreate.handlers.ts
  src/mocks/handlers/popUpListRead/PopUpListRead.handlers.ts
  src/pages/dashboardPage/views/BestItem.tsx
  src/pages/dashboardPage/views/DashBoardCongestion.tsx
  src/pages/dashboardPage/views/DashBoardConversionRate.tsx
  src/pages/dashboardPage/views/DashBoardReservation.tsx
  src/pages/dashboardPage/views/DashBoardVisitor.tsx
  src/pages/itemCreatePage/ItemCreatePage.tsx
  src/pages/itemCreatePage/views/ItemCreateInputs.tsx
  src/pages/itemListPage/ItemListPage.tsx
  src/pages/onBoardingPage/views/OnBoardingLogin.tsx
  src/pages/popUpCreatePage/views/PopUpInfoArea.tsx
  src/pages/popUpCreatePage/views/PopUpInput.tsx
  src/pages/popUpListPage/PopUpListPage.tsx
  src/router/Router.tsx
  src/types/DashboardType.ts
  src/types/api/ApiRequestType.ts
  src/utils/FormatDay.ts
Labels: ♻️ refactor

#49 fix: 배포전 기능 검토
  src/apis/DashBoardApi.ts
  src/apis/ItemListApi.ts
  src/components/common/CustomInput.tsx
  src/components/common/Loading.tsx
  src/components/common/NoImageComp.tsx
  src/components/layouts/GlobalLayout.tsx
  src/constants/onboarding/ContentDesc.ts
  src/hooks/usePopUpCreate.ts
  src/mocks/handlers/dashboard/BestItems.handlers.ts
  src/mocks/handlers/dashboard/ConversionRead.handlers.ts
  src/mocks/handlers/dashboard/Questionnaire.handlers.ts
  src/mocks/handlers/dashboard/ReservationDatas.handlers.ts
  src/mocks/handlers/itemList/ItemList.handlers.ts
  src/mocks/handlers/popUpListRead/PopUpListRead.handlers.ts
  src/pages/dashboardPage/views/BestItem.tsx
  src/pages/dashboardPage/views/ConversionRateChart.tsx
  src/pages/dashboardPage/views/CountCard.tsx
  src/pages/dashboardPage/views/DashBoardCustomerTransaction.tsx
  src/pages/dashboardPage/views/DashBoardQuestionnaire.tsx
  src/pages/dashboardPage/views/DashBoardReservation.tsx
  src/pages/dashboardPage/views/ReservationByDayChart.tsx
  src/pages/itemCreatePage/views/ItemCreateInputs.tsx
  src/pages/itemListPage/ItemListPage.tsx
  src/pages/itemListPage/views/ItemDisplay.tsx
  src/pages/popUpCreatePage/PopUpCreatePage.tsx
  src/pages/popUpCreatePage/views/PopUpInfoArea.tsx
  src/pages/popUpListPage/PopUpListPage.tsx
  src/pages/popUpListPage/views/PopUpCard.tsx
  src/types/api/ApiResponseType.ts
  src/utils/ReservationColorMapper.ts
Labels: ✨ feature
