Repository popi-official/popi-manager-client, pull requests merged in 2025-06, with the labels that each got.

#51 chore: Playwright 설정 추가
  .github/workflows/CI.yml
  .gitignore
  chromatic.config.json
  package-lock.json
  package.json
  playwright.config.ts
  tests/LoginFlow.spec.ts
  tests/global-setup.ts
  tsconfig.app.json
  vite.config.ts
  vitest.config.ts
Labels: ⚙️ chore

#50 fix: API 명세 변경으로 인한 타입 수정
  src/mocks/handlers/dashboard/CustomerTransactionDatas.handlers.ts
  src/pages/dashboardPage/views/DashBoardCustomerTransaction.tsx
  src/types/api/ApiResponseType.ts
Labels: 🐛 bug/error

#57 refactor: 팝업 리스트 스와이퍼 로직 수정
  src/pages/popUpListPage/PopUpListPage.tsx
Labels: ♻️ refactor

#58 test: 대쉬보드 조회 E2E 테스트 구현
  src/pages/dashboardPage/views/BestItem.tsx
  src/pages/dashboardPage/views/DashBoardCongestion.tsx
  src/pages/dashboardPage/views/DashBoardConversionRate.tsx
  src/pages/dashboardPage/views/DashBoardCustomerTransaction.tsx
  src/pages/dashboardPage/views/DashBoardQuestionnaire.tsx
  src/pages/dashboardPage/views/DashBoardReservation.tsx
  src/pages/dashboardPage/views/DashBoardVisitor.tsx
  tests/DashboardFlow.spec.ts
Labels: ✅ test

#59 test: 상품 조회 E2E 테스트
  eslint.config.js
  src/pages/itemListPage/views/ItemDisplay.tsx
  tests/ItemListFlow.spec.ts
Labels: ✅ test

#62 feat: 알림 websocket 연결
  index.html
  package-lock.json
  package.json
  src/components/common/NavBar.tsx
  src/components/noticeModal/NoticeModal.tsx
  src/components/noticeModal/views/NoticeItem.tsx
  src/mocks/handlers/noticeModal/StockNotificationList.handlers.ts
  src/stores/useNotificationStore.ts
  src/utils/NotificationSocket.ts
  vite.config.ts
Labels: ✨ feature

#65 refactor: 대시보드 페이지 리팩토링
  src/components/common/NavBar.tsx
  src/components/noticeModal/NoticeModal.tsx
  src/components/noticeModal/views/NoticeItem.tsx
  src/index.css
  src/main.tsx
  src/pages/dashboardPage/views/BestItem.tsx
  src/pages/dashboardPage/views/DashBoardCustomerTransaction.tsx
  src/pages/dashboardPage/views/DashBoardQuestionnaire.tsx
  src/pages/dashboardPage/views/DashBoardReservation.tsx
  src/utils/NotificationSocket.ts
Labels: ♻️ refactor

#64 feat: 조건부 공통 컴포넌트 구현
  .github/workflows/CI.yml
  scripts/generate-lighthouse-config.js
  src/components/common/ConditionalComponent.tsx
  src/components/common/QueryComponent.tsx
  src/pages/itemListPage/ItemListPage.tsx
Labels: ✨ feature

#67 refactor: 대시보드 페이지 리팩토링 (QueryComponent 사용)
  src/components/common/QueryComponent.tsx
  src/pages/dashboardPage/DashBoardPage.tsx
  src/pages/dashboardPage/views/BestItem.tsx
  src/pages/dashboardPage/views/DashBoardCongestion.tsx
  src/pages/dashboardPage/views/DashBoardConversionRate.tsx
  src/pages/dashboardPage/views/DashBoardCustomerTransaction.tsx
  src/pages/dashboardPage/views/DashBoardQuestionnaire.tsx
  src/pages/dashboardPage/views/DashBoardReservation.tsx
  src/pages/dashboardPage/views/DashBoardVisitor.tsx
Labels: ♻️ refactor

#66 refactor: 온보딩 페이지 리팩토링
  src/pages/onBoardingPage/OnBoardingPage.tsx
  src/pages/onBoardingPage/views/OnBoardingContents.tsx
Labels: ♻️ refactor

#70 refactor: components 내부 구조 개선 및 분리
  src/components/common/ConditionalComponent.tsx
  src/components/common/Modal.tsx
  src/components/common/NavBar.tsx
  src/components/common/QueryComponent.tsx
  src/components/ui/CustomButton.stories.tsx
  src/components/ui/CustomButton.tsx
  src/components/ui/CustomInput.stories.tsx
  src/components/ui/CustomInput.tsx
  src/components/ui/Loading.tsx
  src/components/ui/NoImageComp.tsx
  src/components/ui/Skeleton.tsx
  src/pages/dashboardPage/views/@common/CountCard.tsx
  src/pages/dashboardPage/views/@common/CustomBlurDot.tsx
  src/pages/dashboardPage/views/@common/CustomCursor.tsx
  src/pages/dashboardPage/views/@common/CustomTooltip.tsx
  src/pages/dashboardPage/views/@common/DropdownFilter.tsx
  src/pages/dashboardPage/views/@common/NoDataComp.tsx
  src/pages/dashboardPage/views/@common/Title.tsx
  src/pages/dashboardPage/views/ConversionRateChart.tsx
  src/pages/dashboardPage/views/DashBoardConversionRate.tsx
  src/pages/dashboardPage/views/DashBoardCustomerTransaction.tsx
  src/pages/dashboardPage/views/DashBoardQuestionnaire.tsx
  src/pages/dashboardPage/views/DashBoardReservation.tsx
  src/pages/dashboardPage/views/DashBoardVisitor.tsx
  src/pages/dashboardPage/views/ReservationByDayChart.tsx
  src/pages/dashboardPage/views/VisitorPieChart.tsx
  src/pages/dashboardPage/views/bestItem/BestItemCardImage.tsx
  src/pages/dashboardPage/views/bestItem/index.tsx
  src/pages/dashboardPage/views/congestion/CongestionChart.tsx
  src/pages/dashboardPage/views/congestion/index.tsx
  src/pages/itemCreatePage/ItemCreatePage.tsx
  src/pages/itemCreatePage/views/ItemCreateInputs.tsx
  src/pages/onBoardingPage/views/OnBoardingLogin.tsx
  src/pages/popUpCreatePage/views/PopUpInfoArea.tsx
  src/pages/popUpListPage/PopUpListPage.tsx
  src/utils/NotificationSocket.ts
Labels: ♻️ refactor

#71 refactor: 대시보드 Visitor 리팩토링
  src/apis/DashBoardApi.ts
  src/assets/webps/onBoarding/onBoarding2.webp
  src/assets/webps/onBoarding/onBoarding3.webp
  src/constants/onboarding/ContentDesc.ts
  src/hooks/api/useDashboardApi.ts
  src/mocks/browser.ts
  src/mocks/handlers/dashboard/VisitorDatas.handlers.ts
  src/pages/dashboardPage/index.tsx
  src/pages/dashboardPage/views/@common/CustomTooltip.tsx
  src/pages/dashboardPage/views/visitor/Label.tsx
  src/pages/dashboardPage/views/visitor/VisitorPieChart.tsx
  src/pages/dashboardPage/views/visitor/VisitorPieLegend.tsx
  src/pages/dashboardPage/views/visitor/index.tsx
  src/pages/itemCreatePage/index.tsx
  src/pages/itemListPage/index.tsx
  src/pages/onBoardingPage/index.tsx
  src/pages/onBoardingPage/views/OnBoardingLogin.tsx
  src/pages/orderListPage/index.tsx
  src/pages/orderListPage/views/OrderListItem.tsx
  src/pages/popUpCreatePage/index.tsx
  src/pages/popUpListPage/index.tsx
  src/router/Router.tsx
  src/types/api/ApiResponseType.ts
  src/utils/NotificationSocket.ts
  tests/DashboardFlow.spec.ts
Labels: ♻️ refactor

#73 refactor: 대시보드 Reservation & CT 리팩토링
  src/components/ui/Skeleton.tsx
  src/pages/dashboardPage/index.tsx
  src/pages/dashboardPage/views/@common/NoDataComp.tsx
  src/pages/dashboardPage/views/DashBoardCustomerTransaction.tsx
  src/pages/dashboardPage/views/DashBoardReservation.tsx
  src/pages/dashboardPage/views/bestItem/BestItemCardImage.tsx
  src/pages/dashboardPage/views/bestItem/index.tsx
  src/pages/dashboardPage/views/congestion/index.tsx
  src/pages/dashboardPage/views/customerTransaction/index.tsx
  src/pages/dashboardPage/views/reservation/ReservationByDayChart.tsx
  src/pages/dashboardPage/views/reservation/index.tsx
  src/pages/dashboardPage/views/visitor/index.tsx
  src/utils/ReservationColorMapper.ts
Labels: ♻️ refactor

#75 chore: E2E CI 수정
  .github/workflows/CI.yml
  playwright.config.ts
Labels: ⚙️ chore

#81 docs: README.md 작성
  README.md
Labels: 📝 documentation
